import '../styles/tailwind.css';
import type { ReactNode } from 'react';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

type RootLayoutProps = {
	children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="pl">
			<body className="bg-theme-primary text-white">{children}</body>
		</html>
	);
}
